CXX = clang++
CXXFLAGS = -std=c++17 -O2 -Wall -Wextra
INCLUDES = -I./JuceLibraryCode -I./Source -I/usr/local/include
DEFINES = -DJUCE_APP_VERSION=1.0.0 -DJUCE_APP_VERSION_HEX=0x10000 -DJUCER_XCODE_MAC_F6D2F4CF=1 -DJUCE_SHARED_CODE=1
LIBS = -framework CoreFoundation -framework CoreGraphics -framework CoreText -framework Cocoa -framework Carbon -framework AudioToolbox -framework CoreAudio -framework CoreMIDI -framework IOKit -framework AGL -framework AudioUnit -framework OpenGL -framework IOSurface -framework QuartzCore -framework AVFoundation -framework Security

SOURCES = test_vocoder_fixes.cpp \
          Source/PhasedVocoder.cpp \
          Source/DspEngineUtilities.h \
          JuceLibraryCode/include_juce_core.cpp \
          JuceLibraryCode/include_juce_audio_basics.cpp \
          JuceLibraryCode/include_juce_dsp.cpp

OBJECTS = $(SOURCES:.cpp=.o)
TARGET = test_vocoder_fixes

.PHONY: all clean

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) $(OBJECTS) $(LIBS) -o $(TARGET)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) $(DEFINES) -c $< -o $@

clean:
	rm -f $(OBJECTS) $(TARGET)

test: $(TARGET)
	./$(TARGET)